fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    profiled: "https://github.com/unibet/puppet-profiled.git"
    augeasproviders_shellvar: "https://github.com/hercules-team/augeasproviders_shellvar.git"
  symlinks:
    lastpass: "#{source_dir}"
